export {Cat} from "./cat";
export {Cd} from "./cd";
export {Clear} from "./clear";
// export {Cp} from "./cp";
export {Echo} from "./echo";
// export {Exit} from "./exit";
export {False} from "./false";
// export {Grep} from "./grep";
export {Help} from "./help";
export {Ls} from "./ls";
export {Man} from "./man";
export {Mkdir} from "./mkdir";
// export {Mv} from "./mv";
export {Pwd} from "./pwd";
export {Touch} from "./touch";
export {True} from "./true";
