name: Node.js CI

on:
    push:
        branches-ignore:
            - master
            - gh-pages

jobs:
    tests:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: src

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: "npm"
            -   run: npm ci
            -   run: npm run test:prod

    e2e:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: .

        strategy:
            matrix:
                node-version: [ 16.x ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: "npm"
            -   run: npm ci
            -   run: npm run e2e:ci
